steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/gcp-deployment-441717/flask-backend:latest', '.']
    dir: 'flask-app'

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/gcp-deployment-441717/flask-backend:latest']

  # Step 3: Reset the Compute Engine instance to apply the updated container
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['compute', 'instances', 'reset', 'flask-app-instance', '--zone', 'us-central1-a']

# Define the logs bucket
logs_bucket: 'gs://log-bucket0705'  # The bucket you created for logs

# Optional: Specify service account if needed
# If you're not using a service account, you can remove the below section.
service_account: 'your-service-account@your-project-id.iam.gserviceaccount.com'  # Replace with your actual service account

# Optional: Define timeout for build (if necessary)
timeout: '1200s'  # 20 minutes

