steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/gcp-deployment-441717/flask-backend:latest', '.']
    dir: 'flask-app'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/gcp-deployment-441717/flask-backend:latest']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['compute', 'instances', 'reset', 'flask-app-instance', '--zone', 'us-central1-a']
